### ISSUE TITLE
Handling of array's in the DataModel

### ISSUE THREAD

**Issue by binomaiheu** [pixel-ports/pyngsi#1]
First of all thanks a lot for this library, really useful ! I wanted to use the DataModel class to push entities to an Orion context broker which have Array type attributes. In particular i would like to represent a forecast which spans over multiple days in the same entity, think of a temperature forecasts of daily maxima for the next few days. 

When i add this as : 

```
m = DataModel(id="id1", type="WeatherObserved")
m.add("forecastValue", [1., 2., 3., 4.,5] )
```
the python list correctly gets interpreted as a Sequence (see ngsi.py at line 62), but on line 66 it gets directly assigned to the attribute, without the `{ "value": ..., "type": ... }`, causing the `sink.write(m.json())` to fail with 

```
SinkException: cannot write to SinkHttp : 400 Client Error: Bad Request for url: http://127.0.0.1:1026/v2/entities?options=upsert
Server returned : {"error":"BadRequest","description":"attribute must be a JSON object, unless keyValues option is used"}
record={"id": "id1", "type": "WeatherObserved", "forecastValue": [1.0, 2.0, 3.0, 4.0]}
```

replacing line 66 with 
```
#self[name] = v if t == "Array" else {"value": v, "type": t}
self[name] = {"value": v, "type": t}
```

would work (tested this) and the entity gets correctly created in the broker : 
```
{
  "id": "id1",
  "type": "WeatherObserved",
  "forecastValue": {
    "value": [
      1.0,
      2.0,
      3.0,
      4.0
    ],
    "type": "Array"
  }
}
```

with the type "Array'. I'm not sure why the body of the Sequence get's reassigned on line 66, when i check ngsi specs it should be entirely ok to assign structured values, see : https://fiware-orion.readthedocs.io/en/1.7.0/user/structured_attribute_valued/index.html ? Or was there another reason for this ? 

Thnks !
bino

**Comment by fbattello** [comment]
Happy the lib can help !
Sorry for the delay notifications were not enabled and I've just seen your issue
I have to ensure there is no impact or odd reason related to this line 66 I possibly wrote for the needs of a NGSI agent.
Anyway the correction will meet the ngsi specs you've pointed out
fabien

**Comment by fbattello** [comment]
No other reason for this.
Welcome type "Array" !
