### ISSUE TITLE
Float datatype should be Number

### ISSUE THREAD

**Issue by MichelSc** [pixel-ports/pyngsi#3]
See file ngsi.py, line 64.
Float is no ngsi datatype.
Compatibility with Quantumleap is broken.
We should use "Number" instead of "Float".
See:

Fiware data models:
-	https://fiware-datamodels.readthedocs.io/en/latest/guidelines/index.html
-	“When possible reuse schema.org data types (Text, Number, DateTime, StructuredValue, etc.).”

Schema.org
-	https://schema.org/DataType
-	https://schema.org/Number

**Comment by fbattello** [comment]
Fixed in v2.1.8 : "Number" used instead of "Float" and "Integer".
Sorry for the inconvenience with QuantumLeap.
