### ISSUE TITLE
problems installing

### ISSUE THREAD

**Issue by albertoabellagarcia** [pixel-ports/pyngsi#6]
xxx:~$ pip install pyngsi
Collecting pyngsi
  ERROR: Could not find a version that satisfies the requirement pyngsi (from versions: none)
ERROR: No matching distribution found for pyngsi

python version 
xxx:~$ python3 -V
Python 3.7.4

Is it possible to use it with this python version or should I update to a newer one?

**Comment by fbattello** [comment]
Python 3.8+ is required.
Mainly because pyngsi makes use of dataclasses.
